name: Docs

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs workflow temporarily disabled"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs deployment temporarily disabled"
